# -----------------------------------------------------------------------------------------------------------------------------
# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
#
# -----------------------------------------------------------------------------------------------------------------------------

name: Java CI with Maven for "https://www.99-bottles-of-beer.net" project
env:
  APPLICATION_NAME : "MyFlask"
  PACKAGE_NAME     : "flask_deploy_ver_${{ github.sha }}"

on:
  
  pull_request:
    branches: "main"

jobs:
  build_1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven for "https://www.99-bottles-of-beer.net" project
      run: mvn -B package --file pom.xml
      
    - name: Print APPLICATION NAME
      run: echo "Application name:${{env.APPLICATION_NAME}}"
      
    - name: Print PACKAGE_NAME
      run: echo "Package name:${{env.PACKAGE_NAME}}"
      
    - name: test some packages if they exist
      run: aws --version 
